manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
    - name: brisk84
      url-base: https://github.com/brisk84
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: brisk84
      revision: 2bebca0065f853156f78f7eac832e68b82683202
  self:
    path: config
