manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
    - name: brisk84
      url-base: https://github.com/brisk84
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: brisk84
      revision: 3851fe11018c79ff11e4177b4345259a85db866e
  self:
    path: config
